global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80

  traefik:
    address: :8080

  tls:
    address: :443

api:
  insecure: true
  dashboard: true

providers:
  docker:
    exposedByDefault: false

  # swarm:
  #   exposedByDefault: false

log:
  level: INFO

certificatesResolvers:
  le:
    acme:
      email: stas@ekb.ru
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: httpreq
        resolvers:
          - 8.8.8.8
