name: rClone

services:
  http:
    image: rclone/rclone:latest
    # privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
    devices:
      - /dev/fuse
    command:
      - serve
      - http
      - /etc
      - --addr
      - 0.0.0.0:80
    ports:
      - 1488:80
