name: rClone

services:
  http:
    image: rclone/rclone:latest
    command:
      - serve
      - http
      - /etc
      - --addr
      - 0.0.0.0:80
    ports:
      - 1488:80

  mount:
    image: rclone/rclone:latest
    depends_on:
      sidecar:
        condition: service_completed_successfully
    # privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
    devices:
      - /dev/fuse
    volumes:
      - type: volume
        source: config
        target: /config/rclone
        volume:
          subpath: sync/Rclone/config/mount
      - /mnt/shara:/mnt:rshared
    command:
      - mount
      - "serve.http:"
      - /mnt
      - --allow-non-empty

  sh:
    image: alpine
    depends_on:
      - mount
    volumes:
      - /mnt/shara:/mnt:rslave
    init: true
    command:
      - sleep
      - infinity

  sidecar:
    image: ukoloff/sidecar:js
    volumes:
      - config:/config
    working_dir: /config
    environment:
      SIDECAR_GIT_URL: ukoloff/sandbox.docker/sync/Rclone/config#rClone

volumes:
  config:
