name: rClone

services:
  http:
    image: rclone/rclone:latest
    depends_on:
      sidecar:
        condition: service_completed_successfully
    volumes:
      - type: volume
        source: config
        target: /config/rclone
        volume:
          subpath: sync/Rclone/config/http
    command:
      - serve
      - http
      - /etc
      - --addr
      - :80
      - --htpasswd
      - /config/rclone/passwd
      - --dir-cache-time
      - 1s
    ports:
      - 1488:80

  sftp:
    image: rclone/rclone:latest
    volumes:
      - type: volume
        source: config
        target: /config/rclone
        volume:
          subpath: sync/Rclone/config/sftp
    command:
      - serve
      - sftp
      - /etc
      - --addr
      - :22
      - --key
      - /config/rclone/.ssh/id_ed25519
      - --user
      - rclone
      - --authorized-keys
      - /config/rclone/.ssh/authorized_keys
      - --dir-cache-time
      - 1s
    ports:
      - 1422:22

  webdav:
    image: rclone/rclone:latest
    command:
      - serve
      - webdav
      - /etc
      - --addr
      - :80
      - --dir-cache-time
      - 1s
    ports:
      - 1480:80

  mnt88:
    image: rclone/rclone:latest
    depends_on:
      sidecar:
        condition: service_completed_successfully
    # privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
    devices:
      - /dev/fuse
    volumes:
      - type: volume
        source: config
        target: /config/rclone
        volume:
          subpath: sync/Rclone/config/mnt88
      - /mnt/rclone/88:/mnt:rshared
    command:
      - mount
      - "serve.http:"
      - /mnt
      - --allow-non-empty
      - --dir-cache-time
      - 1s

  mnt22:
    image: rclone/rclone:latest
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
    devices:
      - /dev/fuse
    volumes:
      - /mnt/rclone/22:/mnt:rshared
      - type: volume
        source: config
        target: /config/rclone
        volume:
          subpath: sync/Rclone/config/mnt22
    command:
      - mount
      - ":sftp:"
      - --sftp-host
      - sftp
      - --sftp-user
      - rclone
      - --sftp-key-file
      - /config/rclone/.ssh/id_ed25519
      - --allow-non-empty
      - --dir-cache-time
      - 1s
      - /mnt

  mnt80:
    image: rclone/rclone:latest
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
    devices:
      - /dev/fuse
    volumes:
      - /mnt/rclone/80:/mnt:rshared
    command:
      - mount
      - ":webdav:"
      - --webdav-url
      - http://webdav
      - --allow-non-empty
      - --dir-cache-time
      - 1s
      - /mnt

  sh:
    image: alpine
    depends_on:
      - mnt88
      - mnt80
      - mnt22
    volumes:
      - /mnt/rclone/88:/mnt/88:rslave
      - /mnt/rclone/80:/mnt/80:rslave
      - /mnt/rclone/22:/mnt/22:rslave
    init: true
    command:
      - sleep
      - infinity

  sidecar:
    image: ukoloff/sidecar:js
    volumes:
      - config:/config
    working_dir: /config
    environment:
      SIDECAR_GIT_URL: ukoloff/sandbox.docker/sync/Rclone/config#rClone

volumes:
  config:
