services:
  sstp:
    image: ukoloff/sstp
    privileged: true
    volumes:
    - /dev/ppp:/dev/ppp
    - /etc/ssl/uxm:/ssl
    ports:
    - 443:443
    command:
    - uv
    - run
    - sstpd
    - -f
    - /etc/sstpd.ini

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.10.0/24
          ip_range: 192.168.10.128/25
          gateway: 192.168.10.254
