services:
  awg:
    image: vernette/amneziawg
    volumes:
      - type: volume
        source: etc
        target: /etc/amnezia/amneziawg
        volume:
          subpath: amnezia/amneziawg
        read_only: true
    devices:
      - /dev/net/tun:/dev/net/tun # только userspace-режим
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1 # нужно для full-tunnel
    cap_add:
      - NET_ADMIN
    restart: always
    environment:
      WG_QUICK_USERSPACE_IMPLEMENTATION: amneziawg-go
    post_start:
      - command: sh -c "ip route add 10.0.0.0/8 via $(ip route | grep default | awk '{print $3}')"

  tweedledum:
    image: alpine/curl
    command: -s https://api.ipify.org
    network_mode: service:awg
    depends_on:
      - awg

  tweedledee:
    image: alpine/curl
    command: -s https://api.ipify.org
    volumes:
      - etc:/tmp/etc

volumes:
  etc:
