services:
  wireguard:
    image: jordanpotter/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    volumes:
      - config:/etc/wireguard/wg0.conf
    restart: unless-stopped

volumes:
  config:
