services:
  wireguard:
    image: jordanpotter/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    volumes:
      - config:/etc/wireguard/
    restart: unless-stopped

  tweedledum:
    image: curlimages/curl
    command: ifconfig.io
    network_mode: service:wireguard
    depends_on:
      - wireguard

  tweedledee:
    image: curlimages/curl
    command: ifconfig.io

volumes:
  config:
