name: sdcr-go

services:
  go:
    image: ukoloff/golang:dev
    volumes:
      - repo:/repo
    working_dir: /repo
    init: true
    command:
      - sleep
      - infinity
    depends_on:
      sidecar:
        condition: service_completed_successfully

  sidecar:
    image: ukoloff/sidecar:js
    volumes:
      - repo:/repo
    working_dir: /repo
    environment:
      SIDECAR_GIT_URL: ukoloff/sandbox.docker/sidecar?dev=1#sidecar.go

volumes:
  repo:
