name: traefik

services:
  itself:
    image: traefik:v3.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - etc:/etc/traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      HTTPREQ_ENDPOINT: http://netangels
      HTTPREQ_POLLING_INTERVAL: 10
      HTTPREQ_PROPAGATION_TIMEOUT: 300

  whoami:
    image: traefik/whoami
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.rule: Host(`whoami.ekb.ru`)
      traefik.http.routers.whoami.entrypoints: tls
      # traefik.http.services.whoami.loadbalancer.server.port: 80
      traefik.http.routers.whoami.tls.certresolver: le

  netangels:
    image: ukoloff/na01:golang
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NETANGELS_LOGGING: 1

volumes:
  etc:

networks:
  default:
    name: traefik
    attachable: true
