name: traefik

services:
  proxy:
    image: traefik:v3.6
    init: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - etc:/etc/traefik
      - acme:/letsenrypt/
      - type: image
        source: ukoloff/na01:golang
        target: /bin/na01
        image:
          subpath: bin/na01
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    env_file:
      - .env
    environment:
      EXEC_PATH: na01
      EXEC_POLLING_INTERVAL: 10
      EXEC_PROPAGATION_TIMEOUT: 300
      NETANGELS_LOGGING: 1

  whoami:
    image: traefik/whoami
    restart: unless-stopped

volumes:
  etc:
  acme:

networks:
  default:
    name: traefik
    attachable: true
