[http]
type = http
url = http://http

[webdav]
type = webdav
url = http://webdav
vendor = rclone
user = admin
pass = Qr8qjsDcQNQvIfJ_uN9NC7PQdVbf

[sftp]
type = sftp
host = sftp
user = rclone
key_file = /config/rclone/.ssh/id_ed25519
known_hosts_file = /config/rclone/.ssh/known_hosts
