name: sidecar-test

services:
  node:
    image: node:lts-alpine
    volumes:
      - type: tmpfs
        target: /var/cache/apk
    working_dir: /repo
    command:
      - sleep
      - infinity
    stop_signal: SIGKILL
