name: syncThing

services:
  sentinel:
    image: node:lts-alpine
    init: true
    env_file:
      - .env
    command:
      - sleep
      - infinity
    networks:
      - default
      - world

  A: &service
    image: syncthing/syncthing
    restart: unless-stopped
    networks:
      default:
        aliases:
          - sthng
    env_file:
      - .env
    ports:
      - 8887:8384
    volumes:
      - vA:/sync/A
      - vB:/sync/B
      - vC:/sync/C

  B:
    <<: *service
    ports:
      - 8888:8384

  C:
    <<: *service
    ports:
      - 8889:8384

volumes:
  vA:
  vB:
  vC:

networks:
  default:
    internal: true
  world:
