name: syncThing

services:
  sentinel:
    image: alpine
    init: true
    command:
      - sleep
      - infinity
    networks:
      - default
      - world

  A: &service
    image: lscr.io/linuxserver/syncthing:latest
    restart: unless-stopped
    ports:
      - 8887:8384
    volumes:
      - vA:/sync/A
      - vB:/sync/B
      - vC:/sync/C
    networks:
      default:
        aliases:
          - sthng

  B:
    <<: *service
    ports:
      - 8888:8384

  C:
    <<: *service
    ports:
      - 8889:8384

volumes:
  vA:
  vB:
  vC:

networks:
  default:
    internal: true
  world:
