name: s-thing

services:
  dev:
    image: ukoloff/dev:js
    init: true
    env_file:
      - .env
    volumes:
      - repo:/repo
    working_dir: /repo
    command:
      - sleep
      - infinity
    networks:
      - default
      - world

  sidecar:
    image: ukoloff/sidecar:js
    volumes:
      - repo:/repo
    working_dir: /repo
    environment:
      SIDECAR_GIT_URL: ukoloff/sandbox.docker/sync/syncThing?dev=1#syncThing
    networks:
      - world


  A: &service
    image: syncthing/syncthing
    restart: unless-stopped
    networks:
      default:
        aliases:
          - sthng
    env_file:
      - .env
    ports:
      - 8887:8384
    volumes:
      - vA:/sync/A
      - vB:/sync/B
      - vC:/sync/C

  B:
    <<: *service
    ports:
      - 8888:8384

  C:
    <<: *service
    ports:
      - 8889:8384

volumes:
  repo:
  vA:
  vB:
  vC:

networks:
  default:
    internal: true
  world:
