services:
  syncthing:
    image: syncthing/syncthing
    deploy:
      mode: global
    networks:
      default:
        aliases:
          - sthng
    env_file:
      - .env
    volumes:
      - config:/var/syncthing
      - folder:/folders/folder
    labels: &vscode-container-explorer
      com.docker.compose.project: SyncThing@swarm

  dev:
    image: ukoloff/dev:js
    labels: *vscode-container-explorer
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.hostname == swarm01
    init: true
    env_file:
      - .env
    volumes:
      - repo:/repo
    working_dir: /repo
    command:
      - sleep
      - infinity
    networks:
      - default
      - world

  sidecar:
    image: ukoloff/sidecar:js
    restart: on-failure
    labels: *vscode-container-explorer
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.hostname == swarm01
    volumes:
      - repo:/repo
    working_dir: /repo
    environment:
      SIDECAR_GIT_URL: ukoloff/sandbox.docker/sync/syncThing?dev=1#syncThing
    networks:
      - world


volumes:
  config:
  folder:
  repo:

networks:
  default:
    internal: true
  world:
