services:
  syncthing:
    image: syncthing/syncthing
    deploy:
      mode: global
    networks:
      default:
        aliases:
          - sthng
    env_file:
      - .env
    volumes:
      - config:/var/syncthing
      - folder:/folders/folder
    labels:
      com.docker.compose.project: SyncThing@swarm

volumes:
  config:
  folder:

networks:
  default:
    internal: true

