# For docker stack
services:
  daemon:
    image: ukoloff/autolabel:sh
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    network_mode: none
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: servicelist
        target: /config/servicelist.txt
    command:
      - sh
      - /bin/monitor.sh

configs:
  servicelist:
    file: config/servicelist.txt
