# For docker stack
services:
  first: &svc
    image: alpine
    deploy: &deploy
      mode: replicated
      replicas: 1
    command:
      - sleep
      - infinity

  second:
    <<: *svc
    deploy:
      <<: *deploy
      placement:
        constraints:
          - node.labels.running_first == 1
    depends_on:
      - first

  third:
    <<: *svc
    deploy:
      <<: *deploy
      placement:
        constraints:
          - node.labels.running_first == 0
    depends_on:
      - first

  fourth:
    <<: *svc
    deploy:
      <<: *deploy
      placement:
        constraints:
          - node.labels.running_third == 1
    depends_on:
      - third
