# For docker stack
services:
  first: &svc
    image: alpine
    deploy:
      mode: replicated
      replicas: 1
    command:
      - sleep
      - infinity

  second:
    <<: *svc
    deploy:
      placement:
        constraints:
          - node.labels.running_first == 1
    depends_on:
      - first

