http:
  routers:
    api:
      rule: Host(`t5k.docker.ekb.ru`) && PathRegexp(`^/(api|debug)`)
      service: api@internal
      middlewares:
        - t5k-auth
        - terry

    dashboard:
      rule: Host(`t5k.docker.ekb.ru`)
      service: dashboard@internal
      middlewares:
        - t5k-auth
        - terry
      tls:
        domains:
          - main: docker.ekb.ru
            sans: "*.docker.ekb.ru"

  middlewares:
    t5k-auth:
      basicAuth:
        usersFile: /etc/traefik/passwd
