http:
  routers:
    api:
      rule: Host(`t5k.docker.ekb.ru`) && PathRegexp(`/(api|debug)`)
      service: api@internal

    dashboard:
      rule: Host(`t5k.docker.ekb.ru`)
      service: dashboard@internal
