http:
  routers:
    whoami:
      rule: Host(`t5k.docker.ekb.ru`) && PathPrefix(`/whoami`)
      service: whoami

  services:
    whoami:
      loadBalancer:
        servers:
          - url: "http://whoami"
